variable "zone_name" {}
variable "storage_image_reference" {}
variable "subnet_id" {}
variable "network_security_group_id" {}
variable "env" {}
variable "applications" {}
variable "databases" {}
variable "subscription_id" {}
variable "rg_name" {}
variable "dns_resource_group_name" {}